version: "3.9"
services:
  web:
    entrypoint: ["sh", "-c", "echo 'Container started. Pausing...'; sleep infinity"]
    build: .
    volumes:
      - type: bind
        source: ./functions
        target: /home/deno/functions
    ports:
      - "8010:9000"
